name: fr-system
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - pip:
    - numpy==1.24.3
    - opencv-python==4.8.0.74
    - insightface==0.7.3
    - sqlalchemy==2.0.20